all:
	cc main.c read_and_save.c komunikacja.c interpretacja.c algorytm.c mapowanie.c move.c -o explor_tank ../cJSON/cJSON.o -lcurl

test: all
	./explor_tank

memory: all
	valgrind ./explor_tank